### ISSUE TITLE
X and Y offset

### ISSUE THREAD

**Issue by squidnugget07** [mmiddletonn/RLProfilePictures#1]
Hey, i tested your plugin in a game and i saw that the image was just a bit under where the image was supposed to be in 1v1, i tested in 3v3 and it works as it should, i haven't tested 2v2 but i think you should add a offset slider for people with different resolutions for their monitor

**Comment by mmiddletonn** [comment]
Would you mind sharing screenshots of the issue and your interface & display settings? I will try to adjust the math or add a debug slider for fine adjustments. Also, I am currently working on another version that goes around bakkesmod and modifies the avatar textures directly.

**Comment by squidnugget07** [comment]
ok i tried replicating the bug but i cant seem to replicate i, it might be a bug that you fixed with a previous commit but i cant replicate it, ill close this issue unless it happens again
